POST http://localhost:8080/events
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImdyYW50QGdtYWlsLmNvbSIsImV4cCI6MTc0MzQ2MTI5NSwidXNlcklkIjo0fQ.RRgj3ZNCSNHpwoi0p59w3b_iyaWDxH4CY8Y4v-E3Ptc

{
    "Name" : "Test Event 2",
    "Description" : "Test Description",
    "Location" : "test location",
    "DateTime" : "2025-01-01T15:30:00.000Z"
}