POST http://localhost:8080/events
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImdyYW50QGdtYWlsLmNvbSIsImV4cCI6MTc0MzQ2NDU4OCwidXNlcklkIjoxfQ.Ti0LagSzBEeMu7SWLM_Io8l5e9j2KGoBF_tFk4iKzfY

{
    "Name" : "Test Event 2",
    "Description" : "Test Description",
    "Location" : "test location",
    "DateTime" : "2025-01-01T15:30:00.000Z"
}