# sudo docker-compose -p visigo up --build

services:
  VisiGo:
    image: postgres
    container_name: VisiGo.db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: VisiGo.db
    restart: always
    ports:
      - "5441:5432"
    volumes:
      - postgres_visigo:/var/lib/postgresql/data 

volumes:
  postgres_visigo: