POST http://localhost:8080/events
Content-Type: application/json

{
    "Name" : "Test Event",
    "Description" : "Test Description",
    "Location" : "test location",
    "DateTime" : "2025-01-01T15:30:00.000Z"
}