PUT  http://localhost:8080/events/1
Content-Type: application/json

{
    "Name" : "Updated Event",
    "Description" : "Test Description 1",
    "Location" : "test location 1",
    "DateTime" : "2025-01-01T15:30:00.000Z"
}